---

- name: Install redis server
  apt:
    name: redis-server

- name: Configure redis
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  register: redis_config

- name: Restart redis
  systemd: service="redis-server.service" state=restarted enabled=yes daemon_reload=yes
  when: redis_config.changed
