---

- name: Install sentinel
  apt:
    name: redis-sentinel

- name: Configure sentinel
  template: src=sentinel.conf.j2 dest=/etc/redis/sentinel.conf
  register: sentinel_config

- name: Restart sentinel
  systemd: service="redis-sentinel.service" state=restarted enabled=yes daemon_reload=yes
  when: sentinel_config.changed


